insert into users_books (title, author_id) values
('Ring-tailed possum', 4),
('Bird, pied butcher', 3),
('Peccary, white-lipped', 2),
('Lily trotter', 4),
('Darter, african', 1),
('Grey lourie', 3),
('American woodcock', 1),
('Racer snake', 4),
('Galapagos penguin', 2),
('Deer, swamp', 2),
('Steller''s sea lion', 2),
('Grouse, greater sage', 4),
('Yak', 3),
('Peacock, blue', 5),
('Marten, american', 5),
('Pied kingfisher', 5),
('Porcupine, indian', 1),
('African black crake', 5),
('Black-capped capuchin', 5),
('Osprey', 2),
('Openbill stork', 4),
('Chimpanzee', 5),
('Southern ground hornbill', 1),
('White-cheeked pintail', 1),
('Crested screamer', 1),
('White-lipped peccary', 5),
('Cockatoo, roseate', 5),
('Squirrel, uinta ground', 2),
('Orca', 2),
('Heron, black-crowned night', 1),
('Fisher', 2),
('Gull, lava', 3),
('Whale, baleen', 5),
('Deer, swamp', 4),
('Jackrabbit, white-tailed', 5),
('Shrike, crimson-breasted', 4),
('Reindeer', 3),
('White-tailed deer', 4),
('Glossy ibis', 1),
('Blue-breasted cordon bleu', 5);